### ISSUE TITLE
ValidateGroups syntax error

### ISSUE THREAD

**Issue by allisonizsak** [suryasaha/OrthoMCL#2]
When trying to run the ValidateGroups.pl script using the required arguments (--selgroups --consparam etc.) the following error occurs: "Unknown option: consparam". However, if you use just the first letter of each argument (-s -c etc.) then the command works.

Unsuccessful:
perl OrthoMCL/orthomcl.ValidateGroups.pl --selgroups My_orthomcl_real/orthomcl.config --consparam My_orthomcl_real/orthomcl.config_e10_s60 --relparam My_orthomcl_real/orthomcl.config_e5_s30 --map maps.txt --names names.txt 

Successful:
perl OrthoMCL/orthomcl.ValidateGroups.pl -s My_orthomcl_real/orthomcl.config -c My_orthomcl_real/orthomcl.config_e10_s60 -r My_orthomcl_real/orthomcl.config_e5_s30 -m maps.txt -n names.txt

**Comment by suryasaha** [comment]
Seems to be working in perl 5, version 14, subversion 2 (v5.14.2) built for x86_64-linux-gnu-thread-multi
Tested `~/OrthoMCL_PostProcessing/orthomcl.ValidateGroups.pl --selgroups sel.groups.txt -c con.groups.txt -r rel.groups.txt -m maps.txt --names names.tx`
