### ISSUE TITLE
ValidateGroups.pl Incompatible files

### ISSUE THREAD

**Issue by allisonizsak** [suryasaha/OrthoMCL#3]
When I created my maps.txt and names.txt files, I used information from fasta files downloaded from i5k rather than refseq. This didn't inhibit the command from running, but it did interfere with the output. All of the created Validated_clusters\* files were empty. Is there a way to use this script with fasta files in formats other than the refseq format?

**Comment by suryasaha** [comment]
The scripts cannot handle input files in different directories. Put all files in the same directory and execute.

The `orthomcl.convert2Refseq.pl` script can be used to convert fasta and GFF files to Refseq format. I have created `orthomcl.convert2RefseqFasta.pl` for processing only fasta files from i5k.
